SunMaria/Controllers/CategoryController.cs
using System.Linq;
using System.Web.Mvc;
using SunMaria.Areas.Item.Models;

namespace SunMaria.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ItemContext db = new ItemContext();

        public ActionResult Index()
        {
            return PartialView("_CategoryMenu", db.Categories.ToList());
        }
    }
}

SunMaria/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SunMaria.Controllers
{
    public class NewsController : Controller
    {
        // GET: News
        public ActionResult AllNews()
        {
            return View();
        }
        public ViewResult IdNews(int? id)
        {
            if (id == null)
            {
                return View("AllNews");
            }
            string idS = Convert.ToString(id);
            return View(idS);
        }
    }
}

SunMaria/Views/Shared/_CategoryMenu.cshtml
@model IEnumerable<SunMaria.Areas.Item.Models.Categories>
<div class="categories d-lg-flex d-md-none d-none">
    @{
        var headers = Model.Select(category => category.Subgroup).Distinct().ToList();
    }

    @foreach (var header in headers)
    {
        <div class="dropdown">
            <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                @header
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                @foreach (var category in Model.Where(c => c.Subgroup == header))
                {
                    <a class="dropdown-item" href="#">@category.Name</a>
                }
            </div>
        </div>
    }
</div>

SunMaria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet"/>
    <link href="~/Content/Testimonials.css" rel="stylesheet"/>
    <link href="~/Content/Footer-Clean.css" rel="stylesheet"/>
    <link href="~/Content/styles.css" rel="stylesheet"/>

</head>
<body>
<header>
    <nav class="navbar navbar-light navbar-expand-md bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" @Html.ActionLink("SunMaria", "Index", "Home")</a>
            <button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1">
                <span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" @Html.ActionLink("Блог", "Allnews", "News")
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" @Html.ActionLink("Магазин", "list", "Items")</a>
                    </li>

                    @{
                        if (Request.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link"> @User.Identity.Name</a>
                            </li>
                            using (Html.BeginForm("Logoff", "Account", FormMethod.Post, new {id = "logoutForm"}))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" href="javascript:document.getElementById('logoutForm').submit()">Выйти</a>
                                </li>
                            }
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" @Html.ActionLink("Регистрация", "Register", "Account")
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" @Html.ActionLink("Логин", "Login", "Account")
                            </li>
                        }
                    }
                    @if (Request.IsAuthenticated)

                    {
                        <li class="shopping-cart">
                            <a class="nav-link fig"href="@Url.Action("Index", "Cart", new {returnUrl = Request.Url.PathAndQuery})">
                                <img src="/Images/shopping-cart.png" width="30" height="30">
                            </a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>

@{ Html.RenderAction("Index", "Category"); }
@RenderBody()
<div class="footer-clean">
    <footer>
        @if (IsSectionDefined("Footer"))
        {
            @RenderSection("Footer")
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-sm-4 col-md-3 item">
                        <h3>Компания</h3>
                        <ul>
                            <li>
                                <a href="#">О бренде</a>
                            </li>
                            <li>
                                <a href="#">Условия возврата</a>
                            </li>
                            <li>
                                <a href="#">Пользовательское соглашение</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-sm-4 col-md-3 item">
                        <h3>About</h3>
                        <ul>
                            <li>
                                <a href="#">Company</a>
                            </li>
                            <li>
                                <a href="#">Team</a>
                            </li>
                            <li>
                                <a href="#">Legacy</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-sm-4 col-md-3 item">
                        <h3>Руководство по покупкам</h3>
                        <ul>
                            <li>
                                <a href="#">Виды полотен</a>
                            </li>
                            <li>
                                <a href="#">Размерная сетка</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-lg-3 item social">
                        <a href="#">
                            <i class="icon ion-social-facebook"></i>
                        </a>
                        <a href="#">
                            <i class="icon ion-social-twitter"></i>
                        </a>
                        <a href="#">
                            <i class="icon ion-social-instagram"></i>
                        </a>
                        <p class="copyright">©2020 SunMaria<br></p>
                    </div>
                </div>
            </div>
        }
        else
        {
        }
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>